Docs/rtd staging
Infineon/XMC-for-Arduino pull request #302
Opened 2024-09-16 12:43 UTC by ederjc

This PR contains the following changes regarding the RTD documentation:
- Changes from: https://github.com/Infineon/XMC-for-Arduino/pull/301
- Overview table for XMC boards
- Remove not required packages
- Add build workflow & make files for docs

2024-09-16 19:48 UTC, jaenrig-ifx commented
Missing "following URL" copy link?
![image](https://github.com/user-attachments/assets/a434894c-9615-4e96-84bf-b792fc69e701)

And maybe "Arduino Standard" could be "Arduino Reference Language"? 
![image](https://github.com/user-attachments/assets/19e43c4b-d5b0-4544-896f-56e373f2c742)
There is no clear naming for the reference API... but this headline is the closest: 
https://www.arduino.cc/reference/en/
or the ArduinoCore-API which is reference imposed by the types, classes and function signatures.

2024-09-16 19:48 UTC, jaenrig-ifx requested changes
For approval, only adding the json package index URL.

2024-09-17 05:55 UTC, ederjc commented
> For approval, only adding the json package index URL.

Was there, but didn't render properly. Now after some trying around replaced by a [literal block](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks).

2024-09-17 07:17 UTC, jaenrig-ifx approved these changes

2024-09-20 08:25 UTC, merged